// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';
//
// // ...
//
// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
// );

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpGWGdv4shqM0mbDIn4iEwYU6vFXadINo',
    appId: '1:223301687504:web:7d2227f8808eecfee766d5',
    messagingSenderId: '223301687504',
    projectId: 'padhle1',
    authDomain: 'padhle1.firebaseapp.com',
    storageBucket: 'padhle1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Tbas7_nHzGiwc7erOMxwfZLiN30BD1U',
    appId: '1:223301687504:android:400c579f98fbc922e766d5',
    messagingSenderId: '223301687504',
    projectId: 'padhle1',
    storageBucket: 'padhle1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWZS1tl9OG7meBea2D0rx8y0iXgJCCM_w',
    appId: '1:223301687504:ios:9dd29b374a207171e766d5',
    messagingSenderId: '223301687504',
    projectId: 'padhle1',
    storageBucket: 'padhle1.appspot.com',
    iosBundleId: 'com.example.padhle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWZS1tl9OG7meBea2D0rx8y0iXgJCCM_w',
    appId: '1:223301687504:ios:4c430d066b3b5fb7e766d5',
    messagingSenderId: '223301687504',
    projectId: 'padhle1',
    storageBucket: 'padhle1.appspot.com',
    iosBundleId: 'com.example.padhle.RunnerTests',
  );
}
